package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 10 11:16:51 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Cip_VORowImpl extends ViewRowImpl {
    public static final int ENTITY_CIP_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CapitalizeAmount,
        CipCapId,
        CipCapNo,
        CompanyCode,
        CreatedBy,
        CreationDate,
        CumulativeCipCost,
        CurrencyCode,
        GlDate,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        Remarks,
        Status,
        WellId,
        Trans_Well,
        WellMasterVO,
        WellMasterVO_Ref;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CAPITALIZEAMOUNT = AttributesEnum.CapitalizeAmount.index();
    public static final int CIPCAPID = AttributesEnum.CipCapId.index();
    public static final int CIPCAPNO = AttributesEnum.CipCapNo.index();
    public static final int COMPANYCODE = AttributesEnum.CompanyCode.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CUMULATIVECIPCOST = AttributesEnum.CumulativeCipCost.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int GLDATE = AttributesEnum.GlDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int WELLID = AttributesEnum.WellId.index();
    public static final int TRANS_WELL = AttributesEnum.Trans_Well.index();
    public static final int WELLMASTERVO = AttributesEnum.WellMasterVO.index();
    public static final int WELLMASTERVO_REF = AttributesEnum.WellMasterVO_Ref.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Cip_VORowImpl() {
    }

    /**
     * Gets Cip_EO entity object.
     * @return the Cip_EO
     */
    public EntityImpl getCip_EO() {
        return (EntityImpl) getEntity(ENTITY_CIP_EO);
    }

    /**
     * Gets the attribute value for CAPITALIZE_AMOUNT using the alias name CapitalizeAmount.
     * @return the CAPITALIZE_AMOUNT
     */
    public BigDecimal getCapitalizeAmount() {
        return (BigDecimal) getAttributeInternal(CAPITALIZEAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for CAPITALIZE_AMOUNT using the alias name CapitalizeAmount.
     * @param value value to set the CAPITALIZE_AMOUNT
     */
    public void setCapitalizeAmount(BigDecimal value) {
        setAttributeInternal(CAPITALIZEAMOUNT, value);
    }

    /**
     * Gets the attribute value for CIP_CAP_ID using the alias name CipCapId.
     * @return the CIP_CAP_ID
     */
    public BigDecimal getCipCapId() {
        return (BigDecimal) getAttributeInternal(CIPCAPID);
    }

    /**
     * Sets <code>value</code> as attribute value for CIP_CAP_ID using the alias name CipCapId.
     * @param value value to set the CIP_CAP_ID
     */
    public void setCipCapId(BigDecimal value) {
        setAttributeInternal(CIPCAPID, value);
    }

    /**
     * Gets the attribute value for CIP_CAP_NO using the alias name CipCapNo.
     * @return the CIP_CAP_NO
     */
    public String getCipCapNo() {
        return (String) getAttributeInternal(CIPCAPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CIP_CAP_NO using the alias name CipCapNo.
     * @param value value to set the CIP_CAP_NO
     */
    public void setCipCapNo(String value) {
        setAttributeInternal(CIPCAPNO, value);
    }

    /**
     * Gets the attribute value for COMPANY_CODE using the alias name CompanyCode.
     * @return the COMPANY_CODE
     */
    public String getCompanyCode() {
        return (String) getAttributeInternal(COMPANYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_CODE using the alias name CompanyCode.
     * @param value value to set the COMPANY_CODE
     */
    public void setCompanyCode(String value) {
        setAttributeInternal(COMPANYCODE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CUMULATIVE_CIP_COST using the alias name CumulativeCipCost.
     * @return the CUMULATIVE_CIP_COST
     */
    public BigDecimal getCumulativeCipCost() {
        return (BigDecimal) getAttributeInternal(CUMULATIVECIPCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for CUMULATIVE_CIP_COST using the alias name CumulativeCipCost.
     * @param value value to set the CUMULATIVE_CIP_COST
     */
    public void setCumulativeCipCost(BigDecimal value) {
        setAttributeInternal(CUMULATIVECIPCOST, value);
    }

    /**
     * Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @return the CURRENCY_CODE
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @param value value to set the CURRENCY_CODE
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for GL_DATE using the alias name GlDate.
     * @return the GL_DATE
     */
    public Timestamp getGlDate() {
        return (Timestamp) getAttributeInternal(GLDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GL_DATE using the alias name GlDate.
     * @param value value to set the GL_DATE
     */
    public void setGlDate(Timestamp value) {
        setAttributeInternal(GLDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for WELL_ID using the alias name WellId.
     * @return the WELL_ID
     */
    public BigDecimal getWellId() {
        return (BigDecimal) getAttributeInternal(WELLID);
    }

    /**
     * Sets <code>value</code> as attribute value for WELL_ID using the alias name WellId.
     * @param value value to set the WELL_ID
     */
    public void setWellId(BigDecimal value) {
        setAttributeInternal(WELLID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Well.
     * @return the Trans_Well
     */
    public String getTrans_Well() {
        BigDecimal OrgId = null;
                String orgName = null;
                if (getWellId() != null) {
                    OrgId = getWellId();
                    Row[] orgRows;
                    orgRows = getWellMasterVO_Ref().getFilteredRows("WellId", OrgId);
                    if (orgRows.length > 0) {
                        orgName = orgRows[0].getAttribute("WellName").toString();
                    }
                    return orgName;

                } else {
        return (String) getAttributeInternal(TRANS_WELL);
                }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Well.
     * @param value value to set the  Trans_Well
     */
    public void setTrans_Well(String value) {
        setAttributeInternal(TRANS_WELL, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WellMasterVO.
     */
    public RowSet getWellMasterVO() {
        return (RowSet) getAttributeInternal(WELLMASTERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WellMasterVO_Ref.
     */
    public RowSet getWellMasterVO_Ref() {
        return (RowSet) getAttributeInternal(WELLMASTERVO_REF);
    }
}

