package model.vo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 10 11:16:52 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Cip_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Cip_VOImpl() {
    }

    /**
     * Returns the variable value for BV_Id.
     * @return variable value for BV_Id
     */
    public BigDecimal getBV_Id() {
        return (BigDecimal) ensureVariableManager().getVariableValue("BV_Id");
    }

    /**
     * Sets <code>value</code> for variable BV_Id.
     * @param value value to bind as BV_Id
     */
    public void setBV_Id(BigDecimal value) {
        ensureVariableManager().setVariableValue("BV_Id", value);
    }
}

