package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 08 18:45:25 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RetirementLines_VORowImpl extends ViewRowImpl {
    public static final int ENTITY_RETIREMENTLINES_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AccumDeprnCost,
        AssetCategoryId,
        AssetCost,
        CreatedBy,
        CreationDate,
        DeprnReserveCost,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        RetirementCost,
        TransactionId,
        TransactionLineId,
        CategoryLines_ROVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ACCUMDEPRNCOST = AttributesEnum.AccumDeprnCost.index();
    public static final int ASSETCATEGORYID = AttributesEnum.AssetCategoryId.index();
    public static final int ASSETCOST = AttributesEnum.AssetCost.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DEPRNRESERVECOST = AttributesEnum.DeprnReserveCost.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int RETIREMENTCOST = AttributesEnum.RetirementCost.index();
    public static final int TRANSACTIONID = AttributesEnum.TransactionId.index();
    public static final int TRANSACTIONLINEID = AttributesEnum.TransactionLineId.index();
    public static final int CATEGORYLINES_ROVO = AttributesEnum.CategoryLines_ROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RetirementLines_VORowImpl() {
    }

    /**
     * Gets RetirementLines_EO entity object.
     * @return the RetirementLines_EO
     */
    public EntityImpl getRetirementLines_EO() {
        return (EntityImpl) getEntity(ENTITY_RETIREMENTLINES_EO);
    }

    /**
     * Gets the attribute value for ACCUM_DEPRN_COST using the alias name AccumDeprnCost.
     * @return the ACCUM_DEPRN_COST
     */
    public BigDecimal getAccumDeprnCost() {
        return (BigDecimal) getAttributeInternal(ACCUMDEPRNCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCUM_DEPRN_COST using the alias name AccumDeprnCost.
     * @param value value to set the ACCUM_DEPRN_COST
     */
    public void setAccumDeprnCost(BigDecimal value) {
        setAttributeInternal(ACCUMDEPRNCOST, value);
    }

    /**
     * Gets the attribute value for ASSET_CATEGORY_ID using the alias name AssetCategoryId.
     * @return the ASSET_CATEGORY_ID
     */
    public BigDecimal getAssetCategoryId() {
        return (BigDecimal) getAttributeInternal(ASSETCATEGORYID);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSET_CATEGORY_ID using the alias name AssetCategoryId.
     * @param value value to set the ASSET_CATEGORY_ID
     */
    public void setAssetCategoryId(BigDecimal value) {
        setAttributeInternal(ASSETCATEGORYID, value);
    }

    /**
     * Gets the attribute value for ASSET_COST using the alias name AssetCost.
     * @return the ASSET_COST
     */
    public BigDecimal getAssetCost() {
        return (BigDecimal) getAttributeInternal(ASSETCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSET_COST using the alias name AssetCost.
     * @param value value to set the ASSET_COST
     */
    public void setAssetCost(BigDecimal value) {
        setAttributeInternal(ASSETCOST, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for DEPRN_RESERVE_COST using the alias name DeprnReserveCost.
     * @return the DEPRN_RESERVE_COST
     */
    public BigDecimal getDeprnReserveCost() {
        return (BigDecimal) getAttributeInternal(DEPRNRESERVECOST);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPRN_RESERVE_COST using the alias name DeprnReserveCost.
     * @param value value to set the DEPRN_RESERVE_COST
     */
    public void setDeprnReserveCost(BigDecimal value) {
        setAttributeInternal(DEPRNRESERVECOST, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for RETIREMENT_COST using the alias name RetirementCost.
     * @return the RETIREMENT_COST
     */
    public BigDecimal getRetirementCost() {
        return (BigDecimal) getAttributeInternal(RETIREMENTCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for RETIREMENT_COST using the alias name RetirementCost.
     * @param value value to set the RETIREMENT_COST
     */
    public void setRetirementCost(BigDecimal value) {
        setAttributeInternal(RETIREMENTCOST, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_ID using the alias name TransactionId.
     * @return the TRANSACTION_ID
     */
    public BigDecimal getTransactionId() {
        return (BigDecimal) getAttributeInternal(TRANSACTIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_ID using the alias name TransactionId.
     * @param value value to set the TRANSACTION_ID
     */
    public void setTransactionId(BigDecimal value) {
        setAttributeInternal(TRANSACTIONID, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_LINE_ID using the alias name TransactionLineId.
     * @return the TRANSACTION_LINE_ID
     */
    public BigDecimal getTransactionLineId() {
        return (BigDecimal) getAttributeInternal(TRANSACTIONLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_LINE_ID using the alias name TransactionLineId.
     * @param value value to set the TRANSACTION_LINE_ID
     */
    public void setTransactionLineId(BigDecimal value) {
        setAttributeInternal(TRANSACTIONLINEID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CategoryLines_ROVO.
     */
    public RowSet getCategoryLines_ROVO() {
        return (RowSet) getAttributeInternal(CATEGORYLINES_ROVO);
    }
}

