package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 23 15:24:02 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UopMaster_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_UOPMASTER_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BusinessUnitId,
        CreatedBy,
        CreationDate,
        GlTransferFlag,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        Period,
        Status,
        UopDeprHdrId,
        Trans_BusinessName,
        CompanyCode,
        CurrencyCode,
        ProdUnitsEquity,
        UnitsNetReserve,
        WellId,
        AssetBookCode,
        Trans_CompCode,
        Trans_AssetBookName,
        Trans_WellName,
        Trans_Search_cmpy,
        Trans_Search_WellName,
        Trans_Search_WellCode,
        UopLines_VO,
        Xxhr_BusinessUnit_view_ROVO1,
        Xxhr_BusinessUnit_view_Ref,
        Period_Name_ROVO,
        Company_ROVO,
        CompanyAssetDetails_ROVO,
        WellCodeDetails_ROVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int GLTRANSFERFLAG = AttributesEnum.GlTransferFlag.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int PERIOD = AttributesEnum.Period.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int UOPDEPRHDRID = AttributesEnum.UopDeprHdrId.index();
    public static final int TRANS_BUSINESSNAME = AttributesEnum.Trans_BusinessName.index();
    public static final int COMPANYCODE = AttributesEnum.CompanyCode.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int PRODUNITSEQUITY = AttributesEnum.ProdUnitsEquity.index();
    public static final int UNITSNETRESERVE = AttributesEnum.UnitsNetReserve.index();
    public static final int WELLID = AttributesEnum.WellId.index();
    public static final int ASSETBOOKCODE = AttributesEnum.AssetBookCode.index();
    public static final int TRANS_COMPCODE = AttributesEnum.Trans_CompCode.index();
    public static final int TRANS_ASSETBOOKNAME = AttributesEnum.Trans_AssetBookName.index();
    public static final int TRANS_WELLNAME = AttributesEnum.Trans_WellName.index();
    public static final int TRANS_SEARCH_CMPY = AttributesEnum.Trans_Search_cmpy.index();
    public static final int TRANS_SEARCH_WELLNAME = AttributesEnum.Trans_Search_WellName.index();
    public static final int TRANS_SEARCH_WELLCODE = AttributesEnum.Trans_Search_WellCode.index();
    public static final int UOPLINES_VO = AttributesEnum.UopLines_VO.index();
    public static final int XXHR_BUSINESSUNIT_VIEW_ROVO1 = AttributesEnum.Xxhr_BusinessUnit_view_ROVO1.index();
    public static final int XXHR_BUSINESSUNIT_VIEW_REF = AttributesEnum.Xxhr_BusinessUnit_view_Ref.index();
    public static final int PERIOD_NAME_ROVO = AttributesEnum.Period_Name_ROVO.index();
    public static final int COMPANY_ROVO = AttributesEnum.Company_ROVO.index();
    public static final int COMPANYASSETDETAILS_ROVO = AttributesEnum.CompanyAssetDetails_ROVO.index();
    public static final int WELLCODEDETAILS_ROVO = AttributesEnum.WellCodeDetails_ROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UopMaster_VORowImpl() {
    }

    /**
     * Gets UopMaster_EO entity object.
     * @return the UopMaster_EO
     */
    public EntityImpl getUopMaster_EO() {
        return (EntityImpl) getEntity(ENTITY_UOPMASTER_EO);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for GL_TRANSFER_FLAG using the alias name GlTransferFlag.
     * @return the GL_TRANSFER_FLAG
     */
    public String getGlTransferFlag() {
        return (String) getAttributeInternal(GLTRANSFERFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for GL_TRANSFER_FLAG using the alias name GlTransferFlag.
     * @param value value to set the GL_TRANSFER_FLAG
     */
    public void setGlTransferFlag(String value) {
        setAttributeInternal(GLTRANSFERFLAG, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for PERIOD using the alias name Period.
     * @return the PERIOD
     */
    public String getPeriod() {
        return (String) getAttributeInternal(PERIOD);
    }

    /**
     * Sets <code>value</code> as attribute value for PERIOD using the alias name Period.
     * @param value value to set the PERIOD
     */
    public void setPeriod(String value) {
        setAttributeInternal(PERIOD, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for UOP_DEPR_HDR_ID using the alias name UopDeprHdrId.
     * @return the UOP_DEPR_HDR_ID
     */
    public BigDecimal getUopDeprHdrId() {
        return (BigDecimal) getAttributeInternal(UOPDEPRHDRID);
    }

    /**
     * Sets <code>value</code> as attribute value for UOP_DEPR_HDR_ID using the alias name UopDeprHdrId.
     * @param value value to set the UOP_DEPR_HDR_ID
     */
    public void setUopDeprHdrId(BigDecimal value) {
        setAttributeInternal(UOPDEPRHDRID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_BusinessName.
     * @return the Trans_BusinessName
     */
    public String getTrans_BusinessName() {
        BigDecimal OrgId = null;
        String orgName = null;
        if (getBusinessUnitId() != null) {
            OrgId = getBusinessUnitId();
            Row[] orgRows;
            orgRows = getXxhr_BusinessUnit_view_Ref().getFilteredRows("BuId", OrgId);
            if (orgRows.length > 0) {
                orgName = orgRows[0].getAttribute("BuName").toString();

            }
            return orgName;

        } else {
        return (String) getAttributeInternal(TRANS_BUSINESSNAME);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_BusinessName.
     * @param value value to set the  Trans_BusinessName
     */
    public void setTrans_BusinessName(String value) {
        setAttributeInternal(TRANS_BUSINESSNAME, value);
    }   

    /**
     * Gets the attribute value for COMPANY_CODE using the alias name CompanyCode.
     * @return the COMPANY_CODE
     */
    public String getCompanyCode() {
        return (String) getAttributeInternal(COMPANYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_CODE using the alias name CompanyCode.
     * @param value value to set the COMPANY_CODE
     */
    public void setCompanyCode(String value) {
        setAttributeInternal(COMPANYCODE, value);
    }

    /**
     * Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @return the CURRENCY_CODE
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @param value value to set the CURRENCY_CODE
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for PROD_UNITS_EQUITY using the alias name ProdUnitsEquity.
     * @return the PROD_UNITS_EQUITY
     */
    public BigDecimal getProdUnitsEquity() {
        return (BigDecimal) getAttributeInternal(PRODUNITSEQUITY);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_UNITS_EQUITY using the alias name ProdUnitsEquity.
     * @param value value to set the PROD_UNITS_EQUITY
     */
    public void setProdUnitsEquity(BigDecimal value) {
        setAttributeInternal(PRODUNITSEQUITY, value);
    }


    /**
     * Gets the attribute value for UNITS_NET_RESERVE using the alias name UnitsNetReserve.
     * @return the UNITS_NET_RESERVE
     */
    public BigDecimal getUnitsNetReserve() {
        return (BigDecimal) getAttributeInternal(UNITSNETRESERVE);
    }

    /**
     * Sets <code>value</code> as attribute value for UNITS_NET_RESERVE using the alias name UnitsNetReserve.
     * @param value value to set the UNITS_NET_RESERVE
     */
    public void setUnitsNetReserve(BigDecimal value) {
        setAttributeInternal(UNITSNETRESERVE, value);
    }

    /**
     * Gets the attribute value for WELL_ID using the alias name WellId.
     * @return the WELL_ID
     */
    public BigDecimal getWellId() {
        return (BigDecimal) getAttributeInternal(WELLID);
    }

    /**
     * Sets <code>value</code> as attribute value for WELL_ID using the alias name WellId.
     * @param value value to set the WELL_ID
     */
    public void setWellId(BigDecimal value) {
        setAttributeInternal(WELLID, value);
    }

    /**
     * Gets the attribute value for ASSET_BOOK_CODE using the alias name AssetBookCode.
     * @return the ASSET_BOOK_CODE
     */
    public String getAssetBookCode() {
        return (String) getAttributeInternal(ASSETBOOKCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSET_BOOK_CODE using the alias name AssetBookCode.
     * @param value value to set the ASSET_BOOK_CODE
     */
    public void setAssetBookCode(String value) {
        setAttributeInternal(ASSETBOOKCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_CompCode.
     * @return the Trans_CompCode
     */
    public String getTrans_CompCode() {
        String compCode = null;
        String compName = null;
        String compCodeName = null;
        if (getCompanyCode() != null) {
            compCode = getCompanyCode();
            Row[] orgRows;
            orgRows = getCompanyAssetDetails_ROVO().getFilteredRows("CompanyCode", compCode);
            if (orgRows.length > 0) {
                compCode = orgRows[0].getAttribute("CompanyCode").toString();
                compName = orgRows[0].getAttribute("CompName").toString();
                compCodeName=compCode+" - "+compName;
            }
            return compCodeName;
        } else {
            return (String) getAttributeInternal(TRANS_COMPCODE);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_CompCode.
     * @param value value to set the  Trans_CompCode
     */
    public void setTrans_CompCode(String value) {
        setAttributeInternal(TRANS_COMPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_AssetBookName.
     * @return the Trans_AssetBookName
     */
    public String getTrans_AssetBookName() {
        String assertCode = null;
        String assertName = null;
        if (getAssetBookCode() != null) {
            assertCode = getAssetBookCode();
            Row[] orgRows;
            orgRows = getCompanyAssetDetails_ROVO().getFilteredRows("AssetBookCode", assertCode);
            if (orgRows.length > 0) {
                assertName = orgRows[0].getAttribute("AssetBookName").toString();

            }
            return assertName;
        } else {
        
        return (String) getAttributeInternal(TRANS_ASSETBOOKNAME);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_AssetBookName.
     * @param value value to set the  Trans_AssetBookName
     */
    public void setTrans_AssetBookName(String value) {
        setAttributeInternal(TRANS_ASSETBOOKNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_WellName.
     * @return the Trans_WellName
     */
    public String getTrans_WellName() {
        BigDecimal wellId = null;
        String wellCode = null;
        String wellName = null;
        String wellCodeName = null;
        if (getWellId() != null) {
            wellId = getWellId();
            Row[] orgRows;
            orgRows = getWellCodeDetails_ROVO().getFilteredRows("WellId", wellId);
            if (orgRows.length > 0) {
                wellCode = orgRows[0].getAttribute("WellCode").toString();
                wellName = orgRows[0].getAttribute("WellName").toString();
                wellCodeName = wellCode + " - " + wellName;

            }
            return wellCodeName;
        } else {

            return (String) getAttributeInternal(TRANS_WELLNAME);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_WellName.
     * @param value value to set the  Trans_WellName
     */
    public void setTrans_WellName(String value) {
        setAttributeInternal(TRANS_WELLNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Search_cmpy.
     * @return the Trans_Search_cmpy
     */
    public String getTrans_Search_cmpy() {
        String compCode = null;
        String compName = null;
        //String compCodeName = null;
        if (getCompanyCode() != null) {
            compCode = getCompanyCode();
            Row[] orgRows;
            orgRows = getCompanyAssetDetails_ROVO().getFilteredRows("CompanyCode", compCode);
            if (orgRows.length > 0) {
               // compCode = orgRows[0].getAttribute("CompanyCode").toString();
                compName = orgRows[0].getAttribute("CompName").toString();
                //compCodeName=compCode+" - "+compName;
            }
            return compName;
        } else {
        return (String) getAttributeInternal(TRANS_SEARCH_CMPY);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Search_cmpy.
     * @param value value to set the  Trans_Search_cmpy
     */
    public void setTrans_Search_cmpy(String value) {
        setAttributeInternal(TRANS_SEARCH_CMPY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Search_WellName.
     * @return the Trans_Search_WellName
     */
    public String getTrans_Search_WellName() {
        BigDecimal wellId= null;
      //  String wellCode = null;
                String wellName = null;
               // String wellCodeName = null;
                if (getWellId() != null) {
                    wellId = getWellId();
                    Row[] orgRows;
                    orgRows = getWellCodeDetails_ROVO().getFilteredRows("WellId", wellId);
                    if (orgRows.length > 0) {
                       // wellCode = orgRows[0].getAttribute("WellCode").toString();
                        wellName = orgRows[0].getAttribute("WellName").toString();
                        //wellCodeName=wellCode+" - "+wellName;

                    }
                    return wellName;
                } else {
        return (String) getAttributeInternal(TRANS_SEARCH_WELLNAME);}
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Search_WellCode.
     * @return the Trans_Search_WellCode
     */
    public String getTrans_Search_WellCode() {
        BigDecimal wellId= null;
        String wellCode = null;
                //String wellName = null;
               // String wellCodeName = null;
                if (getWellId() != null) {
                    wellId = getWellId();
                    Row[] orgRows;
                    orgRows = getWellCodeDetails_ROVO().getFilteredRows("WellId", wellId);
                    if (orgRows.length > 0) {
                        wellCode = orgRows[0].getAttribute("WellCode").toString();
                       // wellName = orgRows[0].getAttribute("WellName").toString();
                        //wellCodeName=wellCode+" - "+wellName;

                    }
                    return wellCode;
                } else {
        return (String) getAttributeInternal(TRANS_SEARCH_WELLCODE);}
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UopLines_VO.
     */
    public RowIterator getUopLines_VO() {
        return (RowIterator) getAttributeInternal(UOPLINES_VO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Xxhr_BusinessUnit_view_ROVO1.
     */
    public RowSet getXxhr_BusinessUnit_view_ROVO1() {
        return (RowSet) getAttributeInternal(XXHR_BUSINESSUNIT_VIEW_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Xxhr_BusinessUnit_view_Ref.
     */
    public RowSet getXxhr_BusinessUnit_view_Ref() {
        return (RowSet) getAttributeInternal(XXHR_BUSINESSUNIT_VIEW_REF);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Period_Name_ROVO.
     */
    public RowSet getPeriod_Name_ROVO() {
        return (RowSet) getAttributeInternal(PERIOD_NAME_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Company_ROVO.
     */
    public RowSet getCompany_ROVO() {
        return (RowSet) getAttributeInternal(COMPANY_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CompanyAssetDetails_ROVO.
     */
    public RowSet getCompanyAssetDetails_ROVO() {
        return (RowSet) getAttributeInternal(COMPANYASSETDETAILS_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WellCodeDetails_ROVO.
     */
    public RowSet getWellCodeDetails_ROVO() {
        return (RowSet) getAttributeInternal(WELLCODEDETAILS_ROVO);
    }
}

