package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 27 11:50:25 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UopLines_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UopLines_VOImpl() {
    }
}

