package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 20 17:43:22 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WellChild_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WellChild_VOImpl() {
    }
}

