package model.am;


import java.math.BigDecimal;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;

import java.util.ArrayList;

import model.am.common.Oando_AM;

import model.ro.Lookup_View_ROVOImpl;

import model.vo.CipMaster_VOImpl;
import model.vo.Cip_VOImpl;
import model.vo.Retirement_VOImpl;
import model.vo.UopLines_VOImpl;
import model.vo.UopMaster_VOImpl;
import model.vo.WellChild_VOImpl;
import model.vo.WellMasterVOImpl;

import oracle.jbo.ApplicationModule;
import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 22 17:52:17 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Oando_AMImpl extends ApplicationModuleImpl implements ApplicationModule, Oando_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public Oando_AMImpl() {
    }

    /**
     * Container's getter for Business_Group_View_ROVO.
     * @return Business_Group_View_ROVO
     */
    public ViewObjectImpl getBusiness_Group_View_ROVO() {
        return (ViewObjectImpl) findViewObject("Business_Group_View_ROVO");
    }

    /**
     * Container's getter for Employee_Depnd_View_ROVO.
     * @return Employee_Depnd_View_ROVO
     */
    public ViewObjectImpl getEmployee_Depnd_View_ROVO() {
        return (ViewObjectImpl) findViewObject("Employee_Depnd_View_ROVO");
    }

    /**
     * Container's getter for Employee_View_ROVO.
     * @return Employee_View_ROVO
     */
    public ViewObjectImpl getEmployee_View_ROVO() {
        return (ViewObjectImpl) findViewObject("Employee_View_ROVO");
    }

    /**
     * Container's getter for Lookup_View_ROVO.
     * @return Lookup_View_ROVO
     */


    /**
     * Container's getter for Country_ROVO1.
     * @return Country_ROVO1
     */
    public ViewObjectImpl getCountry_ROVO1() {
        return (ViewObjectImpl) findViewObject("Country_ROVO1");
    }

    /**
     * Container's getter for RelationShip_ROVO.
     * @return RelationShip_ROVO
     */
    public ViewObjectImpl getRelationShip_ROVO() {
        return (ViewObjectImpl) findViewObject("RelationShip_ROVO");
    }

    /**
     * Container's getter for Xxgl_Ledgers1.
     * @return Xxgl_Ledgers1
     */
    public ViewObjectImpl getXxgl_Ledgers1() {
        return (ViewObjectImpl) findViewObject("Xxgl_Ledgers1");
    }

    /**
     * Container's getter for Xxhr_BusinessUnit_view_ROVO1.
     * @return Xxhr_BusinessUnit_view_ROVO1
     */
    public ViewObjectImpl getXxhr_BusinessUnit_view_ROVO1() {
        return (ViewObjectImpl) findViewObject("Xxhr_BusinessUnit_view_ROVO1");
    }

    /**
     * Container's getter for WellMasterVO.
     * @return WellMasterVO
     */
    public WellMasterVOImpl getWellMasterVO() {
        return (WellMasterVOImpl) findViewObject("WellMasterVO");
    }

    /**
     * Container's getter for WellDtlsVO.
     * @return WellDtlsVO
     */
    public ViewObjectImpl getWellDtlsVO() {
        return (ViewObjectImpl) findViewObject("WellDtlsVO");
    }

    /**
     * Container's getter for Code_Combination_ROVO1.
     * @return Code_Combination_ROVO1
     */
    public ViewObjectImpl getCode_Combination_ROVO1() {
        return (ViewObjectImpl) findViewObject("Code_Combination_ROVO1");
    }

    /**
     * Container's getter for Period_Name_ROVO.
     * @return Period_Name_ROVO
     */
    public ViewObjectImpl getPeriod_Name_ROVO() {
        return (ViewObjectImpl) findViewObject("Period_Name_ROVO");
    }

    /**
     * Container's getter for UopMaster_VO.
     * @return UopMaster_VO
     */
    public UopMaster_VOImpl getUopMaster_VO() {
        return (UopMaster_VOImpl) findViewObject("UopMaster_VO");
    }

    /**
     * Container's getter for UopLines_VO.
     * @return UopLines_VO
     */
    public UopLines_VOImpl getUopLines_VO() {
        return (UopLines_VOImpl) findViewObject("UopLines_VO");
    }

    /**
     * Container's getter for WellsMaster_VL1.
     * @return WellsMaster_VL1
     */
    public ViewLinkImpl getWellsMaster_VL1() {
        return (ViewLinkImpl) findViewLink("WellsMaster_VL1");
    }

    /**
     * Container's getter for UopHdrLines_VL1.
     * @return UopHdrLines_VL1
     */
    public ViewLinkImpl getUopHdrLines_VL1() {
        return (ViewLinkImpl) findViewLink("UopHdrLines_VL1");
    }

    public String createUop(BigDecimal hdrId) {
        //  String p_errorMessgae = null;
        String p_errorCode = null;
        try {
            String stmt1 = "begin xxfa_uop_depr_pkg.create_line(:p_uop_depr_hdr_id,:p_return_code,:p_return_msg); end;";
            CallableStatement cst = null;
            cst = this.getDBTransaction().createCallableStatement(stmt1, 0);
            cst.setObject("p_uop_depr_hdr_id", hdrId);
            cst.registerOutParameter("p_return_code", Types.VARCHAR);
            cst.registerOutParameter("p_return_msg", Types.VARCHAR);
            cst.executeUpdate();
            if (cst.getObject("p_return_code") != null) {
                // p_errorMessgae = cst.getObject("p_return_msg").toString();
                p_errorCode = cst.getObject("p_return_code").toString();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return p_errorCode;

    }

    public String refreshUop(BigDecimal hdrId) {
        //  String p_errorMessgae = null;
        String p_errorCode = null;
        try {
            String stmt1 = "begin xxfa_uop_depr_pkg.UPDATE_LINE(:p_uop_depr_hdr_id,:p_return_code,:p_return_msg); end;";
            CallableStatement cst = null;
            cst = this.getDBTransaction().createCallableStatement(stmt1, 0);
            cst.setObject("p_uop_depr_hdr_id", hdrId);
            cst.registerOutParameter("p_return_code", Types.VARCHAR);
            cst.registerOutParameter("p_return_msg", Types.VARCHAR);
            cst.executeUpdate();
            if (cst.getObject("p_return_code") != null) {
                // p_errorMessgae = cst.getObject("p_return_msg").toString();
                p_errorCode = cst.getObject("p_return_code").toString();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return p_errorCode;

    }

    public ArrayList periodUop(String company_code, String asset_book, BigDecimal well_id, String period) {
        //        String p_errorMessgae = null;
        //                String p_errorCode =null;
        ArrayList list = new ArrayList();
        try {
            String stmt1 =
                "begin xxfa_uop_depr_pkg.valid_uop_period(:p_company_code,:p_asset_book,:p_well_id,:p_period,:p_return_code,:p_return_msg); end;";
            CallableStatement cst = null;
            cst = this.getDBTransaction().createCallableStatement(stmt1, 0);
            cst.setObject("p_company_code", company_code);
            cst.setObject("p_asset_book", asset_book);
            cst.setObject("p_well_id", well_id);
            cst.setObject("p_period", period);
            cst.registerOutParameter("p_return_code", Types.VARCHAR);
            cst.registerOutParameter("p_return_msg", Types.VARCHAR);
            cst.executeUpdate();
            if (cst.getObject("p_return_code") != null) {
                list.add(cst.getObject("p_return_code").toString());
            } else {
                list.add(" ");
            }
            if (cst.getObject("p_return_msg") != null) {
                list.add(cst.getObject("p_return_msg").toString());
            } else {
                list.add(" ");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;

    }

    /**
     * @param company_code
     * @param well_id
     * @param asset_category_id
     * @param period
     * @return
     */
    public String cipBalance(String company_code, BigDecimal well_id, BigDecimal asset_category_id, String period) {


        String p_errorCode = null;

        // System.out.println("Company Code-- " + company_code);
        // System.out.println("well_id-- " + well_id);
        //  System.out.println("asset_category_id-- " + asset_category_id);
        // System.out.println("period-- -- " + period);
        CallableStatement cst = null;
        String stmt1 = "BEGIN ? := xxfa_uop_depr_pkg.get_cip_balance(?,?,?,?); END;";
        cst = this.getDBTransaction().createCallableStatement(stmt1, 0);
        try {
            cst.setObject(2, company_code);
            cst.setObject(3, well_id);
            cst.setObject(4, asset_category_id);
            cst.setObject(5, period);
            cst.registerOutParameter(1, Types.DECIMAL);
            cst.executeUpdate();
            cst.getObject(1);
            cst.getBigDecimal(1);
            p_errorCode = cst.getBigDecimal(1) == null ? "0" : cst.getBigDecimal(1).toString();
            //  System.out.println("Cip Balance p_errorCode ------------- " + p_errorCode);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return p_errorCode;

    }

    public String deprnReserve(String company_code, BigDecimal well_id, BigDecimal asset_category_id, String period) {


        String p_errorCode = null;
//                System.out.println("came in dep rev");
//                System.out.println("Company Code-- " + company_code);
//                System.out.println("well_id-- " + well_id);
//                System.out.println("asset_category_id-- " + asset_category_id);
//                System.out.println("period-- -- " + period);
        CallableStatement cst = null;
        String stmt1 = "BEGIN ? := xxfa_uop_depr_pkg.get_deprn_reserve(?,?,?,?); END;";
        
        cst = this.getDBTransaction().createCallableStatement(stmt1, 0);
        try {
            cst.setObject(2, company_code);
            cst.setObject(3, well_id);
            cst.setObject(4, asset_category_id);
            cst.setObject(5, period);
            cst.registerOutParameter(1, Types.DECIMAL);
            cst.executeUpdate();
            cst.getObject(1);
            cst.getBigDecimal(1);
            p_errorCode = cst.getBigDecimal(1) == null ? "0" : cst.getBigDecimal(1).toString();
          //  System.out.println("deprnReserve p_errorCode ------------- " + p_errorCode);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return p_errorCode;

    }


    /**
     * Container's getter for Cip_VO1.
     * @return Cip_VO1
     */
    public Cip_VOImpl getCip_VO() {
        return (Cip_VOImpl) findViewObject("Cip_VO");
    }


    /**
     * Container's getter for Company_ROVO1.
     * @return Company_ROVO1
     */
    public ViewObjectImpl getCompany_ROVO() {
        return (ViewObjectImpl) findViewObject("Company_ROVO");
    }

    /**
     * Container's getter for Well_ROVO1.
     * @return Well_ROVO1
     */
    public ViewObjectImpl getWell_ROVO() {
        return (ViewObjectImpl) findViewObject("Well_ROVO");
    }


    /**
     * Container's getter for WellChild_VO1.
     * @return WellChild_VO1
     */
    public WellChild_VOImpl getWellChild_VO() {
        return (WellChild_VOImpl) findViewObject("WellChild_VO");
    }

    /**
     * Container's getter for WellMasChild_VL1.
     * @return WellMasChild_VL1
     */
    public ViewLinkImpl getWellMasChild_VL1() {
        return (ViewLinkImpl) findViewLink("WellMasChild_VL1");
    }

    /**
     * Container's getter for Company_AssetBook_ROVO1.
     * @return Company_AssetBook_ROVO1
     */
    public ViewObjectImpl getCompany_AssetBook_ROVO() {
        return (ViewObjectImpl) findViewObject("Company_AssetBook_ROVO");
    }

    /**
     * Container's getter for CompanyAssetDetails_ROVO1.
     * @return CompanyAssetDetails_ROVO1
     */
    public ViewObjectImpl getCompanyAssetDetails_ROVO() {
        return (ViewObjectImpl) findViewObject("CompanyAssetDetails_ROVO");
    }

    /**
     * Container's getter for WellCodeDetails_ROVO1.
     * @return WellCodeDetails_ROVO1
     */
    public ViewObjectImpl getWellCodeDetails_ROVO() {
        return (ViewObjectImpl) findViewObject("WellCodeDetails_ROVO");
    }


    /**
     * Container's getter for CipMaster_VO1.
     * @return CipMaster_VO1
     */
    public CipMaster_VOImpl getCipMaster_VO() {
        return (CipMaster_VOImpl) findViewObject("CipMaster_VO");
    }

    /**
     * Container's getter for Retirement_VO1.
     * @return Retirement_VO1
     */
    public Retirement_VOImpl getRetirement_VO() {
        return (Retirement_VOImpl) findViewObject("Retirement_VO");
    }
    //
    //    /**
    //     * Container's getter for Lookup_View_ROVO.
    //     * @return Lookup_View_ROVO
    //     */
    //    public model.ro.Lookup_View_ROVOImpl getLookup_View_ROVO() {
    //        return (model.ro.Lookup_View_ROVOImpl) findViewObject("Lookup_View_ROVO");
    //    }

    /**
     * Container's getter for LegalEntity_ROVO1.
     * @return LegalEntity_ROVO1
     */
    public ViewObjectImpl getLegalEntity_ROVO() {
        return (ViewObjectImpl) findViewObject("LegalEntity_ROVO");
    }

    /**
     * Container's getter for CIPAssestCategory_ROVO1.
     * @return CIPAssestCategory_ROVO1
     */
    public ViewObjectImpl getCIPAssestCategory_ROVO() {
        return (ViewObjectImpl) findViewObject("CIPAssestCategory_ROVO");
    }


    /**
     * Container's getter for Attachment_VO1.
     * @return Attachment_VO1
     */
    public ViewObjectImpl getAttachment_VO() {
        return (ViewObjectImpl) findViewObject("Attachment_VO");
    }

    /**
     * Container's getter for AttachmentCip_VL1.
     * @return AttachmentCip_VL1
     */
    public ViewLinkImpl getAttachmentCip_VL() {
        return (ViewLinkImpl) findViewLink("AttachmentCip_VL");
    }

    /**
     * Container's getter for Attachment_VO1.
     * @return Attachment_VO1
     */
    public ViewObjectImpl getAttachment_VO1() {
        return (ViewObjectImpl) findViewObject("Attachment_VO1");
    }

    /**
     * Container's getter for Attachment_Retire_VL1.
     * @return Attachment_Retire_VL1
     */
    public ViewLinkImpl getAttachment_Retire_VL1() {
        return (ViewLinkImpl) findViewLink("Attachment_Retire_VL1");
    }


    /**
     * Container's getter for CipLines_VO1.
     * @return CipLines_VO1
     */
    public ViewObjectImpl getCipLines_VO() {
        return (ViewObjectImpl) findViewObject("CipLines_VO");
    }

    /**
     * Container's getter for CipLines_VL1.
     * @return CipLines_VL1
     */
    public ViewLinkImpl getCipLines_VL() {
        return (ViewLinkImpl) findViewLink("CipLines_VL");
    }


    /**
     * Container's getter for RetirementLines_VO1.
     * @return RetirementLines_VO1
     */
    public ViewObjectImpl getRetirementLines_VO() {
        return (ViewObjectImpl) findViewObject("RetirementLines_VO");
    }

    /**
     * Container's getter for RetireLines_VL1.
     * @return RetireLines_VL1
     */
    public ViewLinkImpl getRetireLines_VL() {
        return (ViewLinkImpl) findViewLink("RetireLines_VL");
    }

    /**
     * Container's getter for Lookup_View_ROVO.
     * @return Lookup_View_ROVO
     */
    public Lookup_View_ROVOImpl getLookup_View_ROVO() {
        return (Lookup_View_ROVOImpl) findViewObject("Lookup_View_ROVO");
    }

    /**
     * Container's getter for PeriodROVO1.
     * @return PeriodROVO1
     */
    public ViewObjectImpl getPeriodROVO() {
        return (ViewObjectImpl) findViewObject("PeriodROVO");
    }

    /**
     * Container's getter for JournalDetails_ROVO1.
     * @return JournalDetails_ROVO1
     */
    public ViewObjectImpl getJournalDetails_ROVO() {
        return (ViewObjectImpl) findViewObject("JournalDetails_ROVO");
    }
}
