package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 12 11:39:25 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CipMaster_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_CIPMASTER_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AssetBookCode,
        CompanyCode,
        CreatedBy,
        CreationDate,
        GlDocSequenceValue,
        GlJeHeaderId,
        GlTransferFlag,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        PeriodName,
        Status,
        TransactionId,
        TransactionNum,
        WellId,
        Trans_CompanyCode,
        Trans_WellName,
        Trans_AssetBookName,
        Trans_category,
        Trans_Select,
        Notes,
        SetFlag,
        Attachment_VO,
        CipLines_VO,
        Period_Name_ROVO,
        CipWell_ROVO,
        WellCodeDetails_ROVO,
        CIPAssestCategory_ROVO,
        PeriodROVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ASSETBOOKCODE = AttributesEnum.AssetBookCode.index();
    public static final int COMPANYCODE = AttributesEnum.CompanyCode.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int GLDOCSEQUENCEVALUE = AttributesEnum.GlDocSequenceValue.index();
    public static final int GLJEHEADERID = AttributesEnum.GlJeHeaderId.index();
    public static final int GLTRANSFERFLAG = AttributesEnum.GlTransferFlag.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int PERIODNAME = AttributesEnum.PeriodName.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TRANSACTIONID = AttributesEnum.TransactionId.index();
    public static final int TRANSACTIONNUM = AttributesEnum.TransactionNum.index();
    public static final int WELLID = AttributesEnum.WellId.index();
    public static final int TRANS_COMPANYCODE = AttributesEnum.Trans_CompanyCode.index();
    public static final int TRANS_WELLNAME = AttributesEnum.Trans_WellName.index();
    public static final int TRANS_ASSETBOOKNAME = AttributesEnum.Trans_AssetBookName.index();
    public static final int TRANS_CATEGORY = AttributesEnum.Trans_category.index();
    public static final int TRANS_SELECT = AttributesEnum.Trans_Select.index();
    public static final int NOTES = AttributesEnum.Notes.index();
    public static final int SETFLAG = AttributesEnum.SetFlag.index();
    public static final int ATTACHMENT_VO = AttributesEnum.Attachment_VO.index();
    public static final int CIPLINES_VO = AttributesEnum.CipLines_VO.index();
    public static final int PERIOD_NAME_ROVO = AttributesEnum.Period_Name_ROVO.index();
    public static final int CIPWELL_ROVO = AttributesEnum.CipWell_ROVO.index();
    public static final int WELLCODEDETAILS_ROVO = AttributesEnum.WellCodeDetails_ROVO.index();
    public static final int CIPASSESTCATEGORY_ROVO = AttributesEnum.CIPAssestCategory_ROVO.index();
    public static final int PERIODROVO = AttributesEnum.PeriodROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CipMaster_VORowImpl() {
    }

    /**
     * Gets CipMaster_EO entity object.
     * @return the CipMaster_EO
     */
    public EntityImpl getCipMaster_EO() {
        return (EntityImpl) getEntity(ENTITY_CIPMASTER_EO);
    }

    /**
     * Gets the attribute value for ASSET_BOOK_CODE using the alias name AssetBookCode.
     * @return the ASSET_BOOK_CODE
     */
    public String getAssetBookCode() {
        return (String) getAttributeInternal(ASSETBOOKCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSET_BOOK_CODE using the alias name AssetBookCode.
     * @param value value to set the ASSET_BOOK_CODE
     */
    public void setAssetBookCode(String value) {
        setAttributeInternal(ASSETBOOKCODE, value);
    }

    /**
     * Gets the attribute value for COMPANY_CODE using the alias name CompanyCode.
     * @return the COMPANY_CODE
     */
    public String getCompanyCode() {
        return (String) getAttributeInternal(COMPANYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_CODE using the alias name CompanyCode.
     * @param value value to set the COMPANY_CODE
     */
    public void setCompanyCode(String value) {
        setAttributeInternal(COMPANYCODE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for GL_DOC_SEQUENCE_VALUE using the alias name GlDocSequenceValue.
     * @return the GL_DOC_SEQUENCE_VALUE
     */
    public BigDecimal getGlDocSequenceValue() {
        return (BigDecimal) getAttributeInternal(GLDOCSEQUENCEVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for GL_DOC_SEQUENCE_VALUE using the alias name GlDocSequenceValue.
     * @param value value to set the GL_DOC_SEQUENCE_VALUE
     */
    public void setGlDocSequenceValue(BigDecimal value) {
        setAttributeInternal(GLDOCSEQUENCEVALUE, value);
    }

    /**
     * Gets the attribute value for GL_JE_HEADER_ID using the alias name GlJeHeaderId.
     * @return the GL_JE_HEADER_ID
     */
    public BigDecimal getGlJeHeaderId() {
        return (BigDecimal) getAttributeInternal(GLJEHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for GL_JE_HEADER_ID using the alias name GlJeHeaderId.
     * @param value value to set the GL_JE_HEADER_ID
     */
    public void setGlJeHeaderId(BigDecimal value) {
        setAttributeInternal(GLJEHEADERID, value);
    }

    /**
     * Gets the attribute value for GL_TRANSFER_FLAG using the alias name GlTransferFlag.
     * @return the GL_TRANSFER_FLAG
     */
    public String getGlTransferFlag() {
        return (String) getAttributeInternal(GLTRANSFERFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for GL_TRANSFER_FLAG using the alias name GlTransferFlag.
     * @param value value to set the GL_TRANSFER_FLAG
     */
    public void setGlTransferFlag(String value) {
        setAttributeInternal(GLTRANSFERFLAG, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for PERIOD_NAME using the alias name PeriodName.
     * @return the PERIOD_NAME
     */
    public String getPeriodName() {
        return (String) getAttributeInternal(PERIODNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PERIOD_NAME using the alias name PeriodName.
     * @param value value to set the PERIOD_NAME
     */
    public void setPeriodName(String value) {
        setAttributeInternal(PERIODNAME, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_ID using the alias name TransactionId.
     * @return the TRANSACTION_ID
     */
    public BigDecimal getTransactionId() {
        return (BigDecimal) getAttributeInternal(TRANSACTIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_ID using the alias name TransactionId.
     * @param value value to set the TRANSACTION_ID
     */
    public void setTransactionId(BigDecimal value) {
        setAttributeInternal(TRANSACTIONID, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_NUM using the alias name TransactionNum.
     * @return the TRANSACTION_NUM
     */
    public String getTransactionNum() {
        return (String) getAttributeInternal(TRANSACTIONNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_NUM using the alias name TransactionNum.
     * @param value value to set the TRANSACTION_NUM
     */
    public void setTransactionNum(String value) {
        setAttributeInternal(TRANSACTIONNUM, value);
    }

    /**
     * Gets the attribute value for WELL_ID using the alias name WellId.
     * @return the WELL_ID
     */
    public BigDecimal getWellId() {
        return (BigDecimal) getAttributeInternal(WELLID);
    }

    /**
     * Sets <code>value</code> as attribute value for WELL_ID using the alias name WellId.
     * @param value value to set the WELL_ID
     */
    public void setWellId(BigDecimal value) {
        setAttributeInternal(WELLID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_CompanyCode.
     * @return the Trans_CompanyCode
     */
    public String getTrans_CompanyCode() {
        BigDecimal type = null;
        String code = null;
        String name = null;
        String nameCode = null;
        if (getWellId() != null) {
            type = (BigDecimal) getWellId();
            Row[] orgRows;
            orgRows = getCipWell_ROVO().getFilteredRows("WellId", type);
            if (orgRows.length > 0) {
                code = orgRows[0].getAttribute("CompanyCode").toString();
                name = orgRows[0].getAttribute("CompanyName").toString();
                nameCode = code + "-" + name;
            }
            return nameCode;
        } else {

            return (String) getAttributeInternal(TRANS_COMPANYCODE);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_CompanyCode.
     * @param value value to set the  Trans_CompanyCode
     */
    public void setTrans_CompanyCode(String value) {
        setAttributeInternal(TRANS_COMPANYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_WellName.
     * @return the Trans_WellName
     */
    public String getTrans_WellName() {
        BigDecimal wellId = null;
        String wellCode = null;
        String wellName = null;
        String wellCodeName = null;
        if (getWellId() != null) {
            wellId = getWellId();
            Row[] orgRows;
            orgRows = getWellCodeDetails_ROVO().getFilteredRows("WellId", wellId);
            if (orgRows.length > 0) {
                wellCode = orgRows[0].getAttribute("WellCode").toString();
                wellName = orgRows[0].getAttribute("WellName").toString();
                wellCodeName = wellCode + " - " + wellName;

            }
            return wellCodeName;
        } else {

            return (String) getAttributeInternal(TRANS_WELLNAME);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_WellName.
     * @param value value to set the  Trans_WellName
     */
    public void setTrans_WellName(String value) {
        setAttributeInternal(TRANS_WELLNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_AssetBookName.
     * @return the Trans_AssetBookName
     */
    public String getTrans_AssetBookName() {
        String assertCode = null;
        String assertName = null;
        if (getAssetBookCode() != null) {
            assertCode = getAssetBookCode();
            Row[] orgRows;
            orgRows = getWellCodeDetails_ROVO().getFilteredRows("AssetBookCode", assertCode);
            if (orgRows.length > 0) {
                assertName = orgRows[0].getAttribute("AssetBookName").toString();

            }
            return assertName;
        } else {

            return (String) getAttributeInternal(TRANS_ASSETBOOKNAME);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_AssetBookName.
     * @param value value to set the  Trans_AssetBookName
     */
    public void setTrans_AssetBookName(String value) {
        setAttributeInternal(TRANS_ASSETBOOKNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_category.
     * @return the Trans_category
     */
    public String getTrans_category() {
        return (String) getAttributeInternal(TRANS_CATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_category.
     * @param value value to set the  Trans_category
     */
    public void setTrans_category(String value) {
        setAttributeInternal(TRANS_CATEGORY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Select.
     * @return the Trans_Select
     */
    public String getTrans_Select() {
        return (String) getAttributeInternal(TRANS_SELECT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Select.
     * @param value value to set the  Trans_Select
     */
    public void setTrans_Select(String value) {
        setAttributeInternal(TRANS_SELECT, value);
    }

    /**
     * Gets the attribute value for NOTES using the alias name Notes.
     * @return the NOTES
     */
    public String getNotes() {
        return (String) getAttributeInternal(NOTES);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTES using the alias name Notes.
     * @param value value to set the NOTES
     */
    public void setNotes(String value) {
        setAttributeInternal(NOTES, value);
    }

    /**
     * Gets the attribute value for SET_FLAG using the alias name SetFlag.
     * @return the SET_FLAG
     */
    public String getSetFlag() {
        return (String) getAttributeInternal(SETFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for SET_FLAG using the alias name SetFlag.
     * @param value value to set the SET_FLAG
     */
    public void setSetFlag(String value) {
        setAttributeInternal(SETFLAG, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Attachment_VO.
     */
    public RowIterator getAttachment_VO() {
        return (RowIterator) getAttributeInternal(ATTACHMENT_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CipLines_VO.
     */
    public RowIterator getCipLines_VO() {
        return (RowIterator) getAttributeInternal(CIPLINES_VO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Period_Name_ROVO.
     */
    public RowSet getPeriod_Name_ROVO() {
        return (RowSet) getAttributeInternal(PERIOD_NAME_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CipWell_ROVO.
     */
    public RowSet getCipWell_ROVO() {
        return (RowSet) getAttributeInternal(CIPWELL_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WellCodeDetails_ROVO.
     */
    public RowSet getWellCodeDetails_ROVO() {
        return (RowSet) getAttributeInternal(WELLCODEDETAILS_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CIPAssestCategory_ROVO.
     */
    public RowSet getCIPAssestCategory_ROVO() {
        return (RowSet) getAttributeInternal(CIPASSESTCATEGORY_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PeriodROVO.
     */
    public RowSet getPeriodROVO() {
        return (RowSet) getAttributeInternal(PERIODROVO);
    }
}

