package model.am.common;

import java.math.BigDecimal;

import java.util.ArrayList;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 23 10:27:19 IST 2019
// ---------------------------------------------------------------------
public interface Oando_AM extends ApplicationModule {
    String createUop(BigDecimal hdrId);

    String refreshUop(BigDecimal hdrId);

    ArrayList periodUop(String company_code, String asset_book, BigDecimal well_id, String period);

    String cipBalance(String company_code, BigDecimal well_id, BigDecimal asset_category_id, String period);

    String deprnReserve(String company_code, BigDecimal well_id, BigDecimal asset_category_id, String period);
}

